(TeX-add-style-hook "cca"
 (lambda ()
    (LaTeX-add-labels
     "sec:cca_form"
     "eq:cca_opt"
     "eq:cca_opt2"
     "eq:cca_lagr"
     "eq:cca_partials"
     "eq:cca_rho"
     "eq:cca_eigval_sys"
     "eq:x2"
     "eq:eigval_sys2"
     "eq:cca_C_eigval"
     "eq:cca_svd_sol"
     "sec:emp_cca"
     "eq:scm"
     "eq:cca_Chat"
     "eq:cca_chat_svd"
     "eq:cca_data_model1"
     "fig:cca_errorbars_low_snr"
     "fig:cca_errorbars_high_snr"
     "fig:cca_errorbars"
     "fig:cca_ks_heatmap"
     "fig:cca_auc_heatmap"
     "prop:raj"
     "eq:icca_chat"
     "eq:icca_rho"
     "fig:icca_errorbars_low_snr"
     "fig:icca_errorbars_high_snf"
     "fig:icca_errorbars"
     "fig:icca_ks_heatmap"
     "fig:icca_auc_heatmap")))

