(TeX-add-style-hook "thesis_proposal"
 (lambda ()
    (LaTeX-add-bibliographies
     "IEEEabrv"
     "cca_bib")
    (LaTeX-add-labels
     "sec:intro"
     "sec:cca"
     "sec:cca_detec"
     "sec:rcca"
     "sec:kcca"
     "sec:mcca"
     "sec:fw"
     "sec:mcca_derivs")
    (TeX-add-symbols
     "xI"
     "xII"
     "xIhat"
     "xIIhat"
     "yI"
     "yII"
     "RI"
     "RII"
     "RIII"
     "RIhat"
     "RIIhat"
     "RIIIhat"
     "wI"
     "wII"
     "Creg"
     "Creghat"
     "Cregtil"
     "Ckcca"
     "Ckccatil"
     "figwidth")
    (TeX-run-style-hooks
     "caption"
     "tikz"
     "latex2e"
     "thesis-umich10"
     "thesis-umich"
     "thesis"
     "my_header"
     "abstract"
     "intro"
     "cca"
     "detection"
     "rcca"
     "kcca"
     "mcca"
     "future_work"
     "appendix")))

