(TeX-add-style-hook "svd_proj"
 (lambda ()
    (LaTeX-add-labels
     "eq:chpt7:data_model"
     "eq:chpt7:yn"
     "fig:chpt7:motiv_full1"
     "fig:chpt7:motiv_orth1"
     "fig:chpt7:motiv_gauss1"
     "fig:chpt7:motiv_full2"
     "fig:chpt7:motiv_orth2"
     "fig:chpt7:motiv_gauss2"
     "fig:chpt7:motivation"
     "sec:chpt7:main_results"
     "assum:x_limit"
     "assum:m_limit"
     "assum:m_b"
     "thm:svd_proj"
     "eq:chpt7:solution"
     "eq:chpt7:ugly"
     "corr:svd_proj_unitary"
     "corr:svd_proj_pt"
     "sec:chpt7:emp_res"
     "eq:chpt7:g_like"
     "fig:chpt7:gauss_pred"
     "fig:chpt7:gauss_like_pred"
     "fig:chpt7:gauss_sv"
     "fig:chpt7:gauss1"
     "fig:chpt7:gauss2"
     "fig:chpt7:gauss"
     "eq:chpt7:fourier"
     "fig:chpt7:ortho_pred"
     "fig:chpt7:fourier_pred"
     "fig:chpt7:ortho_sv"
     "fig:chpt7:ortho1"
     "fig:chpt7:ortho2"
     "fig:chpt7:orth_g"
     "sec:chpt7:concl")))

